version: "3.9"
services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres_password
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always
  server:
    build: 
      dockerfile: Dockerfile
      context: .
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - "3000:3000"